# ══════════════════════════════════════════════════════════
#  kitty — ajustes solo para Linux (lo incluye kitty.conf)
# ══════════════════════════════════════════════════════════
map ctrl+shift+n launch --type=os-window --cwd=current --env NERV_FETCH=1
